<?php

namespace App\Http\Controllers;

use App\Models\Satker;
use App\Models\TabelUser;
use App\Models\User;
use Illuminate\Http\Request;

class SatkerController extends Controller
{
    public function index(){
        $tabel_satker = Satker::all();
        $tabel_user= TabelUser::all();
        return view('satker-data',
            ['tabel_satker'=>$tabel_satker],
            ['tabel_user'=>$tabel_user]);
    }


    public function insert(){
        $kk = User::all();
        return view('satker-create');
        ['title' => 'Tambah Satker'];
    }

    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    // BELUM SELESAIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    
    public function store(Request $request){
        $validatedData = $request->validate([
            'nama_kegiatan'  => 'required|max:100',
            'deskripsi kegiatan' => 'required',
            'created_at' => date("Y-m-d H:i:s")
        ]);

        Kegiatan::create($validatedData);

        $request->session()->flash('success', 'Kegiatan berhasil ditambahkan');
        return redirect('/kegiatan-data');
    }

    public function edit(){
        $kegiatan   = Kegiatan::all();
        return view('kegiatan-update',[
            'title' => 'Edit Kegiatan',
            'kegiatan' => $kegiatan
        ]);
    }

    public function update(){

    }

    public function destroy(){

    }

}
